server:
  port: 8083
spring:
  data:
    redis:
      host: 122.51.54.43
      port: 999
      password: passwd
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719     # 8848修改了限流规则，push给这个http server httpserver将规则注册到sentinel
      eager: true #启动将服务加到dashboard
      filter:
        enabled: false
#      scg:
#        fallback:
#          redirect: https://baidu.com
#          mode: redirect
    gateway:
      routes:
        - id: my
          uri: https://baidu.com
          predicates:
            - Path=/bd
        - id: jd
          uri: https://jd.com
          predicates:
            - Path=/jd
        - id: get
          uri: http://localhost:8082
          predicates:
            - Path=/consumer/depart/**
        - id: list
          uri: http://localhost:8082
          predicates:
            - Path=/consumer/depart/

#          filters:
#            - AddHeader=new-color, yellow
#            - One=oneFilter,one
#            - Two=twoFilter,two

#              =======熔断器
#        - id: all
#          uri: http://localhost:8081
#          predicates:
#            - Path=/**
#          filters:
#            - name: Circuit Breaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fl

#            =========限流
#        - id: all
#          uri: http://localhost:8081
#          predicates:
#            - Path=/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@userKeyResolver}"
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1